# Generated by Django 5.1.6 on 2025-02-15 22:38

import modelcluster.contrib.taggit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurrencerule',
            old_name='by_day',
            new_name='weekday',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='by_set_pos',
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='monthly_week_position',
            field=models.SmallIntegerField(blank=True, help_text='For specifying which week of the month the event occurs (e.g., 1 for first, 2 for second, -1 for last week of the month)', null=True),
        ),
        migrations.AlterField(
            model_name='grouppage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Add tags to help users searching for this group. Please categorise according to existing tags first.', through='group.GroupPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
