# Generated by Django 5.1.5 on 2025-02-03 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupindexpage_remove_groupevent_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupevent',
            name='location_url',
        ),
        migrations.RemoveField(
            model_name='groupsubscription',
            name='cost_per_event',
        ),
        migrations.AddField(
            model_name='groupevent',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link to the venue website for the specific event'),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='voluntary_contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupsubscription',
            name='estimated_cost_per_event',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost per event', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('other', 'Other')], help_text="Select the event frequency. Choose 'Other' for custom frequencies.", max_length=50),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='frequency_other',
            field=models.CharField(blank=True, help_text="Please specify the frequency (e.g. 'Every 6 weeks', 'First Thursday of the month')", max_length=50),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='session_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='grouppage',
            name='gender',
            field=models.CharField(blank=True, choices=[('all', 'All Welcome'), ('women_only', 'Women Only'), ('men_only', 'Men Only'), ('other', 'Other')], default='all', help_text="Select a restricted gender if applicable; 'All Welcome' means no restrictions.", max_length=50),
        ),
        migrations.AlterField(
            model_name='groupsubscription',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='groupsubscription',
            name='offers_discount_on_event_cost',
            field=models.BooleanField(default=False, help_text='Indicates if a discount applies on event cost.'),
        ),
    ]
