# Generated by Django 5.1.5 on 2025-02-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_groupevent_location_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouplink',
            old_name='type',
            new_name='platform',
        ),
    ]
