# Generated by Django 5.1.6 on 2025-02-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_groupevent_gender_restriction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevent',
            name='maximum_age',
            field=models.PositiveIntegerField(blank=True, help_text='Optional maximum age for this event.', null=True),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='minimum_age',
            field=models.PositiveIntegerField(blank=True, help_text='Optional minimum age for this event.', null=True),
        ),
    ]
