# Generated by Django 5.1.5 on 2025-02-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_rename_type_grouplink_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevent',
            name='gender_other',
            field=models.CharField(blank=True, help_text="If you selected 'Other', please specify here", max_length=100),
        ),
        migrations.AddField(
            model_name='grouppage',
            name='gender_other',
            field=models.CharField(blank=True, help_text="If you selected 'Other', please specify here", max_length=100),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='gender',
            field=models.CharField(blank=True, choices=[('all', 'All Welcome'), ('women_only', 'Women Only'), ('men_only', 'Men Only'), ('other', 'Other')], default='all', help_text="Select a restricted gender if applicable; 'All Welcome' means no restrictions.", max_length=50),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Copy this link from the above Google Maps panel, by clicking on the location and copying the link from the popup window that shows.'),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link to the organisers website, if they have a webpage for this specific event.'),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='location_details',
            field=models.TextField(blank=True, help_text='Optional extra location details. Any instructions that might help people find the location not already covered.'),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='voluntary_contribution',
            field=models.BooleanField(default=False, help_text='The event cost is not compulsory to pay.'),
        ),
    ]
